# Generated by Django 4.0.6 on 2022-07-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='laben',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.label'),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default=100.0, max_length=255),
            preserve_default=False,
        ),
    ]
