# Generated by Django 4.0.6 on 2022-07-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='laben',
            new_name='label',
        ),
    ]
